spring:
  application:
    name: StudentApi
  datasource:
    url: jdbc:mysql://localhost:3306/studentrest?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8080